import { readFile, writeFile } from 'node:fs/promises';

const markedSource = await readFile('js/vendor/marked.esm.js', 'utf8');
const sources = [
  'js/version-history.js',
  'js/profile-store.js',
  'js/profile-ui.js',
  'js/events/event-schema.js',
  'js/events/profile-analytics.js',
  'js/events/event-bus.js',
  'js/events/clarity-adapter.js',
  'js/shared/about-dialog.js',
  'js/docs/viewer.js'
];
const viewerSource = (await Promise.all(sources.map(async (source) => '// Source: ' + source + '\n' + await readFile(source, 'utf8')))).join('\n\n');

const markedExport = markedSource.match(/export\{([^;]+)\};/);
const markedBinding = markedExport?.[1].match(/(?:^|,)\s*([A-Za-z_$][\w$]*)\s+as\s+marked(?:\s*,|$)/)?.[1];
if (!markedBinding) throw new Error('Could not locate the Marked parser binding.');

const markedClassic = markedSource
  .replace(/export\{[^;]+\};\s*(?:\/\/# sourceMappingURL=.*)?\s*$/, '')
  .trim();
if (markedClassic === markedSource.trim() || /\bexport\s*\{/.test(markedClassic)) {
  throw new Error('Could not convert the local Marked module into the Rachana classic bundle.');
}

const viewerClassic = viewerSource
  .replace(/^import\s+[^;]+;\s*$/gm, '')
  .replace(/^export\s+(?=(const|class|function|async\s+function)\b)/gm, '')
  .trim();
if (/^(?:import|export)\s/m.test(viewerClassic)) throw new Error('Rachana viewer still contains module syntax.');

const banner = [
  '/* Generated by scripts/build-docs.mjs.',
  ' * Edit js/docs/viewer.js or the vendored parser, then rebuild this file.',
  ' */',
  '(() => {',
  "'use strict';"
].join('\n');

await writeFile('js/docs.bundle.js', banner + '\n\n' + markedClassic + `\n\nconst marked = ${markedBinding};` + '\n\n' + viewerClassic + '\n\n})();\n');
