import { readFile, writeFile } from 'node:fs/promises';

const sources = [
  'js/i18n/en.js',
  'js/i18n/kn.js',
  'js/i18n/i18n.js',
  'js/profile-store.js',
  'js/profile-ui.js',
  'js/events/event-schema.js',
  'js/events/profile-analytics.js',
  'js/events/event-bus.js',
  'js/events/resume-adapter.js',
  'js/events/diksoochi-adapter.js',
  'js/events/clarity-adapter.js',
  'js/events/sentry-adapter.js',
  'js/pwa.js',
  'js/shared/about-dialog.js',
  'js/player/collection-data.js',
  'js/player/audio-player.js',
  'js/player/renderers/gita-700.js',
  'js/player/renderers/registry.js',
  'js/player/editor.js',
  'js/player/player-core.js'
];

const parts = [];
for (const source of sources) {
  let code = await readFile(source, 'utf8');
  code = code
    .replace(/^import\s+[^;]+;\s*$/gm, '')
    .replace(/^export\s+(?=(const|class|function|async\s+function)\b)/gm, '');
  parts.push('// Source: ' + source + '\n' + code.trim());
}

const banner = [
  '/* Generated by scripts/build-player.mjs.',
  ' * Edit the modular source files under js/player/, then rebuild this file.',
  ' */',
  '(() => {',
  "'use strict';"
].join('\n');

await writeFile('js/player.bundle.js', banner + '\n\n' + parts.join('\n\n') + '\n\n})();\n');
