import { readFile, writeFile } from 'node:fs/promises';

const sources = [
  'js/profile-store.js',
  'js/profile-ui.js',
  'js/events/event-schema.js',
  'js/events/profile-analytics.js',
  'js/events/event-bus.js',
  'js/events/resume-adapter.js',
  'js/events/clarity-adapter.js',
  'js/events/sentry-adapter.js',
  'js/pwa.js',
  'js/player2/collection-data.js',
  'js/audio-player.js',
  'js/player2/renderers/gita-700.js',
  'js/player2/renderers/registry.js',
  'js/player2/editor.js',
  'js/player2/player-core.js'
];

const parts = [];
for (const source of sources) {
  let code = await readFile(source, 'utf8');
  code = code
    .replace(/^import\s+[^;]+;\s*$/gm, '')
    .replace(/^export\s+(?=(const|class|function|async\s+function)\b)/gm, '');
  parts.push('// Source: ' + source + '\n' + code.trim());
}

const banner = [
  '/* Generated by scripts/build-player2.mjs.',
  ' * Edit the modular source files under js/player2/, then rebuild this file.',
  ' */',
  '(() => {',
  "'use strict';"
].join('\n');

await writeFile('js/player.bundle.js', banner + '\n\n' + parts.join('\n\n') + '\n\n})();\n');
